/* Generated by Yosys 0.20+70 (git sha1 6e907acf86d, gcc 8.3.1 -fPIC -Os) */

module gpio_control_block(vccd, vssd, vccd1, vssd1, gpio_defaults, resetn, resetn_out, serial_clock, serial_clock_out, serial_load, serial_load_out, mgmt_gpio_in, mgmt_gpio_out, mgmt_gpio_oeb, serial_data_in, serial_data_out, user_gpio_out, user_gpio_oeb, user_gpio_in, pad_gpio_holdover, pad_gpio_slow_sel
, pad_gpio_vtrip_sel, pad_gpio_inenb, pad_gpio_ib_mode_sel, pad_gpio_ana_en, pad_gpio_ana_sel, pad_gpio_ana_pol, pad_gpio_dm, pad_gpio_outenb, pad_gpio_out, pad_gpio_in, one, zero);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  input [12:0] gpio_defaults;
  wire [12:0] gpio_defaults;
  wire gpio_logic1;
  wire gpio_outenb;
  wire mgmt_ena;
  output mgmt_gpio_in;
  wire mgmt_gpio_in;
  input mgmt_gpio_oeb;
  wire mgmt_gpio_oeb;
  input mgmt_gpio_out;
  wire mgmt_gpio_out;
  output one;
  wire one;
  output pad_gpio_ana_en;
  wire pad_gpio_ana_en;
  output pad_gpio_ana_pol;
  wire pad_gpio_ana_pol;
  output pad_gpio_ana_sel;
  wire pad_gpio_ana_sel;
  output [2:0] pad_gpio_dm;
  wire [2:0] pad_gpio_dm;
  output pad_gpio_holdover;
  wire pad_gpio_holdover;
  output pad_gpio_ib_mode_sel;
  wire pad_gpio_ib_mode_sel;
  input pad_gpio_in;
  wire pad_gpio_in;
  output pad_gpio_inenb;
  wire pad_gpio_inenb;
  output pad_gpio_out;
  wire pad_gpio_out;
  output pad_gpio_outenb;
  wire pad_gpio_outenb;
  output pad_gpio_slow_sel;
  wire pad_gpio_slow_sel;
  output pad_gpio_vtrip_sel;
  wire pad_gpio_vtrip_sel;
  input resetn;
  wire resetn;
  output resetn_out;
  wire resetn_out;
  input serial_clock;
  wire serial_clock;
  output serial_clock_out;
  wire serial_clock_out;
  input serial_data_in;
  wire serial_data_in;
  output serial_data_out;
  wire serial_data_out;
  input serial_load;
  wire serial_load;
  output serial_load_out;
  wire serial_load_out;
  wire \shift_register[0] ;
  wire \shift_register[10] ;
  wire \shift_register[11] ;
  wire \shift_register[12] ;
  wire \shift_register[1] ;
  wire \shift_register[2] ;
  wire \shift_register[3] ;
  wire \shift_register[4] ;
  wire \shift_register[5] ;
  wire \shift_register[6] ;
  wire \shift_register[7] ;
  wire \shift_register[8] ;
  wire \shift_register[9] ;
  output user_gpio_in;
  wire user_gpio_in;
  input user_gpio_oeb;
  wire user_gpio_oeb;
  input user_gpio_out;
  wire user_gpio_out;
  inout vccd;
  wire vccd;
  inout vccd1;
  wire vccd1;
  inout vssd;
  wire vssd;
  inout vssd1;
  wire vssd1;
  output zero;
  wire zero;
  sky130_fd_sc_hd__or2b_2 _085_ (
    .A(pad_gpio_inenb),
    .B_N(gpio_outenb),
    .X(_053_)
  );
  sky130_fd_sc_hd__buf_2 _086_ (
    .A(_053_),
    .X(_072_)
  );
  sky130_fd_sc_hd__inv_2 _087_ (
    .A(mgmt_ena),
    .Y(_054_)
  );
  sky130_fd_sc_hd__and3_2 _088_ (
    .A(gpio_outenb),
    .B(mgmt_gpio_oeb),
    .C(mgmt_ena),
    .X(_055_)
  );
  sky130_fd_sc_hd__a21o_2 _089_ (
    .A1(user_gpio_oeb),
    .A2(_054_),
    .B1(_055_),
    .X(pad_gpio_outenb)
  );
  sky130_fd_sc_hd__nand2_2 _090_ (
    .A(mgmt_gpio_oeb),
    .B(pad_gpio_dm[1]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor2_2 _091_ (
    .A(pad_gpio_dm[2]),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__inv_2 _092_ (
    .A(_000_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_2 _093_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__inv_2 _094_ (
    .A(pad_gpio_dm[2]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand3_2 _095_ (
    .A(_060_),
    .B(mgmt_gpio_oeb),
    .C(pad_gpio_dm[1]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__inv_2 _096_ (
    .A(mgmt_gpio_out),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_2 _097_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand3_2 _098_ (
    .A(_059_),
    .B(_063_),
    .C(mgmt_ena),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_2 _099_ (
    .A(_054_),
    .B(user_gpio_out),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_2 _100_ (
    .A(_064_),
    .B(_065_),
    .Y(pad_gpio_out)
  );
  sky130_fd_sc_hd__inv_2 _101_ (
    .A(pad_gpio_in),
    .Y(_001_)
  );
  sky130_fd_sc_hd__buf_6 _102_ (
    .A(resetn),
    .X(_066_)
  );
  sky130_fd_sc_hd__or2_4 _103_ (
    .A(_066_),
    .B(gpio_defaults[0]),
    .X(_067_)
  );
  sky130_fd_sc_hd__buf_6 _104_ (
    .A(_067_),
    .X(_002_)
  );
  sky130_fd_sc_hd__buf_4 _105_ (
    .A(serial_load),
    .X(_068_)
  );
  sky130_fd_sc_hd__inv_2 _106_ (
    .A(_068_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _107_ (
    .A(resetn),
    .Y(_069_)
  );
  sky130_fd_sc_hd__buf_4 _108_ (
    .A(_069_),
    .X(_070_)
  );
  sky130_fd_sc_hd__nand2_2 _109_ (
    .A(_070_),
    .B(gpio_defaults[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__or2_4 _110_ (
    .A(_066_),
    .B(gpio_defaults[2]),
    .X(_071_)
  );
  sky130_fd_sc_hd__buf_6 _111_ (
    .A(_071_),
    .X(_004_)
  );
  sky130_fd_sc_hd__inv_2 _112_ (
    .A(_068_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_2 _113_ (
    .A(_070_),
    .B(gpio_defaults[2]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__or2_4 _114_ (
    .A(_066_),
    .B(gpio_defaults[8]),
    .X(_042_)
  );
  sky130_fd_sc_hd__buf_6 _115_ (
    .A(_042_),
    .X(_006_)
  );
  sky130_fd_sc_hd__inv_2 _116_ (
    .A(_068_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_2 _117_ (
    .A(_070_),
    .B(gpio_defaults[8]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__or2_4 _118_ (
    .A(_066_),
    .B(gpio_defaults[9]),
    .X(_043_)
  );
  sky130_fd_sc_hd__buf_6 _119_ (
    .A(_043_),
    .X(_008_)
  );
  sky130_fd_sc_hd__inv_2 _120_ (
    .A(_068_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_2 _121_ (
    .A(_070_),
    .B(gpio_defaults[9]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__or2_4 _122_ (
    .A(_066_),
    .B(gpio_defaults[3]),
    .X(_044_)
  );
  sky130_fd_sc_hd__buf_6 _123_ (
    .A(_044_),
    .X(_010_)
  );
  sky130_fd_sc_hd__inv_2 _124_ (
    .A(_068_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_2 _125_ (
    .A(_070_),
    .B(gpio_defaults[3]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__or2_4 _126_ (
    .A(_066_),
    .B(gpio_defaults[4]),
    .X(_045_)
  );
  sky130_fd_sc_hd__buf_6 _127_ (
    .A(_045_),
    .X(_012_)
  );
  sky130_fd_sc_hd__inv_2 _128_ (
    .A(_068_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_2 _129_ (
    .A(_070_),
    .B(gpio_defaults[4]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__or2_4 _130_ (
    .A(_066_),
    .B(gpio_defaults[1]),
    .X(_046_)
  );
  sky130_fd_sc_hd__buf_6 _131_ (
    .A(_046_),
    .X(_014_)
  );
  sky130_fd_sc_hd__inv_2 _132_ (
    .A(_068_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_2 _133_ (
    .A(_070_),
    .B(gpio_defaults[1]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__or2_4 _134_ (
    .A(_066_),
    .B(gpio_defaults[10]),
    .X(_047_)
  );
  sky130_fd_sc_hd__buf_6 _135_ (
    .A(_047_),
    .X(_016_)
  );
  sky130_fd_sc_hd__inv_2 _136_ (
    .A(_068_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_2 _137_ (
    .A(_070_),
    .B(gpio_defaults[10]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__or2_4 _138_ (
    .A(_066_),
    .B(gpio_defaults[11]),
    .X(_048_)
  );
  sky130_fd_sc_hd__buf_6 _139_ (
    .A(_048_),
    .X(_018_)
  );
  sky130_fd_sc_hd__inv_2 _140_ (
    .A(_068_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_2 _141_ (
    .A(_070_),
    .B(gpio_defaults[11]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__or2_4 _142_ (
    .A(_066_),
    .B(gpio_defaults[12]),
    .X(_049_)
  );
  sky130_fd_sc_hd__buf_6 _143_ (
    .A(_049_),
    .X(_020_)
  );
  sky130_fd_sc_hd__inv_2 _144_ (
    .A(_068_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_2 _145_ (
    .A(_070_),
    .B(gpio_defaults[12]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__or2_2 _146_ (
    .A(resetn),
    .B(gpio_defaults[5]),
    .X(_050_)
  );
  sky130_fd_sc_hd__buf_2 _147_ (
    .A(_050_),
    .X(_022_)
  );
  sky130_fd_sc_hd__inv_2 _148_ (
    .A(serial_load),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_2 _149_ (
    .A(_069_),
    .B(gpio_defaults[5]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__or2_2 _150_ (
    .A(resetn),
    .B(gpio_defaults[6]),
    .X(_051_)
  );
  sky130_fd_sc_hd__buf_2 _151_ (
    .A(_051_),
    .X(_024_)
  );
  sky130_fd_sc_hd__inv_2 _152_ (
    .A(serial_load),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_2 _153_ (
    .A(_069_),
    .B(gpio_defaults[6]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__or2_2 _154_ (
    .A(resetn),
    .B(gpio_defaults[7]),
    .X(_052_)
  );
  sky130_fd_sc_hd__buf_2 _155_ (
    .A(_052_),
    .X(_026_)
  );
  sky130_fd_sc_hd__inv_2 _156_ (
    .A(serial_load),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_2 _157_ (
    .A(_069_),
    .B(gpio_defaults[7]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _158_ (
    .A(serial_clock),
    .Y(_041_)
  );
  sky130_fd_sc_hd__dfbbn_2 _159_ (
    .CLK_N(_028_),
    .D(\shift_register[0] ),
    .Q(mgmt_ena),
    .Q_N(_083_),
    .RESET_B(_002_),
    .SET_B(_003_)
  );
  sky130_fd_sc_hd__dfbbn_2 _160_ (
    .CLK_N(_029_),
    .D(\shift_register[2] ),
    .Q(pad_gpio_holdover),
    .Q_N(_082_),
    .RESET_B(_004_),
    .SET_B(_005_)
  );
  sky130_fd_sc_hd__dfbbn_2 _161_ (
    .CLK_N(_030_),
    .D(\shift_register[8] ),
    .Q(pad_gpio_slow_sel),
    .Q_N(_081_),
    .RESET_B(_006_),
    .SET_B(_007_)
  );
  sky130_fd_sc_hd__dfbbn_2 _162_ (
    .CLK_N(_031_),
    .D(\shift_register[9] ),
    .Q(pad_gpio_vtrip_sel),
    .Q_N(_080_),
    .RESET_B(_008_),
    .SET_B(_009_)
  );
  sky130_fd_sc_hd__dfbbn_2 _163_ (
    .CLK_N(_032_),
    .D(\shift_register[3] ),
    .Q(pad_gpio_inenb),
    .Q_N(_079_),
    .RESET_B(_010_),
    .SET_B(_011_)
  );
  sky130_fd_sc_hd__dfbbn_2 _164_ (
    .CLK_N(_033_),
    .D(\shift_register[4] ),
    .Q(pad_gpio_ib_mode_sel),
    .Q_N(_078_),
    .RESET_B(_012_),
    .SET_B(_013_)
  );
  sky130_fd_sc_hd__dfbbn_2 _165_ (
    .CLK_N(_034_),
    .D(\shift_register[1] ),
    .Q(gpio_outenb),
    .Q_N(_077_),
    .RESET_B(_014_),
    .SET_B(_015_)
  );
  sky130_fd_sc_hd__dfbbn_2 _166_ (
    .CLK_N(_035_),
    .D(\shift_register[10] ),
    .Q(pad_gpio_dm[0]),
    .Q_N(_000_),
    .RESET_B(_016_),
    .SET_B(_017_)
  );
  sky130_fd_sc_hd__dfbbn_2 _167_ (
    .CLK_N(_036_),
    .D(\shift_register[11] ),
    .Q(pad_gpio_dm[1]),
    .Q_N(_076_),
    .RESET_B(_018_),
    .SET_B(_019_)
  );
  sky130_fd_sc_hd__dfbbn_2 _168_ (
    .CLK_N(_037_),
    .D(\shift_register[12] ),
    .Q(pad_gpio_dm[2]),
    .Q_N(_075_),
    .RESET_B(_020_),
    .SET_B(_021_)
  );
  sky130_fd_sc_hd__dfbbn_2 _169_ (
    .CLK_N(_038_),
    .D(\shift_register[5] ),
    .Q(pad_gpio_ana_en),
    .Q_N(_074_),
    .RESET_B(_022_),
    .SET_B(_023_)
  );
  sky130_fd_sc_hd__dfbbn_2 _170_ (
    .CLK_N(_039_),
    .D(\shift_register[6] ),
    .Q(pad_gpio_ana_sel),
    .Q_N(_073_),
    .RESET_B(_024_),
    .SET_B(_025_)
  );
  sky130_fd_sc_hd__dfbbn_2 _171_ (
    .CLK_N(_040_),
    .D(\shift_register[7] ),
    .Q(pad_gpio_ana_pol),
    .Q_N(_084_),
    .RESET_B(_026_),
    .SET_B(_027_)
  );
  sky130_fd_sc_hd__dfrtp_2 _172_ (
    .CLK(serial_clock),
    .D(serial_data_in),
    .Q(\shift_register[0] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _173_ (
    .CLK(serial_clock),
    .D(\shift_register[0] ),
    .Q(\shift_register[1] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _174_ (
    .CLK(serial_clock),
    .D(\shift_register[1] ),
    .Q(\shift_register[2] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _175_ (
    .CLK(serial_clock),
    .D(\shift_register[2] ),
    .Q(\shift_register[3] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _176_ (
    .CLK(serial_clock),
    .D(\shift_register[3] ),
    .Q(\shift_register[4] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _177_ (
    .CLK(serial_clock),
    .D(\shift_register[4] ),
    .Q(\shift_register[5] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _178_ (
    .CLK(serial_clock),
    .D(\shift_register[5] ),
    .Q(\shift_register[6] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _179_ (
    .CLK(serial_clock),
    .D(\shift_register[6] ),
    .Q(\shift_register[7] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _180_ (
    .CLK(serial_clock),
    .D(\shift_register[7] ),
    .Q(\shift_register[8] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _181_ (
    .CLK(serial_clock),
    .D(\shift_register[8] ),
    .Q(\shift_register[9] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _182_ (
    .CLK(serial_clock),
    .D(\shift_register[9] ),
    .Q(\shift_register[10] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _183_ (
    .CLK(serial_clock),
    .D(\shift_register[10] ),
    .Q(\shift_register[11] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _184_ (
    .CLK(serial_clock),
    .D(\shift_register[11] ),
    .Q(\shift_register[12] ),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _185_ (
    .CLK(_041_),
    .D(\shift_register[12] ),
    .Q(serial_data_out),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__buf_2 _186_ (
    .A(resetn),
    .X(resetn_out)
  );
  sky130_fd_sc_hd__buf_2 _187_ (
    .A(serial_clock),
    .X(serial_clock_out)
  );
  sky130_fd_sc_hd__buf_2 _188_ (
    .A(serial_load),
    .X(serial_load_out)
  );
  sky130_fd_sc_hd__ebufn_2 _189_ (
    .A(pad_gpio_in),
    .TE_B(_072_),
    .Z(mgmt_gpio_in)
  );
  sky130_fd_sc_hd__conb_1 const_source (
    .HI(one),
    .LO(zero),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd)
  );
  sky130_fd_sc_hd__einvp_8 gpio_in_buf (
    .A(_001_),
    .TE(gpio_logic1),
    .VGND(vssd),
    .VNB(vssd),
    .VPB(vccd),
    .VPWR(vccd),
    .Z(user_gpio_in)
  );
  gpio_logic_high gpio_logic_high (
    .gpio_logic1(gpio_logic1),
    .vccd1(vccd1),
    .vssd1(vssd1)
  );
endmodule
